spring:
  datasource:
    password: q01689032365
    url: jdbc:mysql://localhost:3306/sales
    username: root
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 934062765905-fhdgt5sud53m74mlculu0938571psqit.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile